version: '3'

services:
  db:
    image: postgres
    container_name: db_postgres
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: usubop
    ports:
      - "5432:5432"
  web:
    image: test_task_med:v1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=etl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=usubop
      - DATABASE_HOST=db
      - BOT_TOKEN=6501903351:AAGBuLSZX_kRUR782BXJqyZWrdYEphboHsw